version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - pip uninstall aws-sam-cli -y
      - chmod +x bin/makeconfig.sh
      - bin/makeconfig.sh
      - mkdir build
  build:
    commands:
      - cd cdk/assets/lambda/catalogactions
      - yarn
      - cd ../useractions
      - yarn
      - cd ../dynamodbstreams
      - yarn
      - cd ../../..
      - yarn
      - yarn build
      - npx cdk bootstrap
      - npx cdk synth
      - cd assets/lambda/catalogactions
      - rm -rf node_modules
      - yarn install --production --frozen-lockfile
      - cd ../useractions
      - rm -rf node_modules
      - yarn install --production --frozen-lockfile
      - cd ../dynamodbstreams
      - rm -rf node_modules
      - yarn install --production --frozen-lockfile
      - cd ../..
      - npx cdk deploy --all --require-approval never
      - aws cloudformation describe-stacks --stack-name "${proj}Output" --region us-east-1 > cloudformationoutput.json
      - echo "export default {};" > ../src/config.ts
      - node parseCfOutput.js
      - cd ..
      - yarn
      - yarn build
      - cd cdk
      - npx cdk deploy "${proj}S3" --require-approval never --region us-east-1
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
